
export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
}

export type ClassRange = '2-4' | '5-7' | '8-10' | '11-12';

export const questionBank: Record<ClassRange, Question[]> = {
  '2-4': [
    {
      id: 1,
      question: 'Which is the national animal of India?',
      options: ['Lion', 'Tiger', 'Elephant', 'Cow'],
      correctAnswer: 'Tiger',
    },
    {
      id: 2,
      question: 'Which festival is called the Festival of Lights?',
      options: ['Diwali', 'Holi', 'Eid', 'Christmas'],
      correctAnswer: 'Diwali',
    },
    {
      id: 3,
      question: 'Which Indian festival is celebrated with colors?',
      options: ['Diwali', 'Holi', 'Pongal', 'Dussehra'],
      correctAnswer: 'Holi',
    },
    {
      id: 4,
      question: 'Which planet is known as the Red Planet?',
      options: ['Earth', 'Mars', 'Jupiter', 'Venus'],
      correctAnswer: 'Mars',
    },
    {
      id: 5,
      question: 'What is the national flower of India?',
      options: ['Rose', 'Sunflower', 'Lotus', 'Jasmine'],
      correctAnswer: 'Lotus',
    },
    {
      id: 6,
      question: 'Which gas do humans need to breathe?',
      options: ['Hydrogen', 'Carbon dioxide', 'Oxygen', 'Nitrogen'],
      correctAnswer: 'Oxygen',
    },
    {
      id: 7,
      question: 'How many days are in a week?',
      options: ['5', '6', '7', '8'],
      correctAnswer: '7',
    },
    {
      id: 8,
      question: 'What is the capital of India?',
      options: ['Mumbai', 'Kolkata', 'New Delhi', 'Chennai'],
      correctAnswer: 'New Delhi',
    },
    {
      id: 9,
      question: 'Which animal is known as the "King of the Jungle"?',
      options: ['Tiger', 'Lion', 'Giraffe', 'Zebra'],
      correctAnswer: 'Lion',
    },
    {
      id: 10,
      question: 'What do we call a baby dog?',
      options: ['Kitten', 'Puppy', 'Calf', 'Cub'],
      correctAnswer: 'Puppy',
    },
    {
      id: 11,
      question: 'What shape has three sides?',
      options: ['Circle', 'Square', 'Triangle', 'Rectangle'],
      correctAnswer: 'Triangle',
    },
    {
      id: 12,
      question: 'Which insect makes honey?',
      options: ['Ant', 'Bee', 'Butterfly', 'Mosquito'],
      correctAnswer: 'Bee',
    },
    {
      id: 13,
      question: 'What is the color of the sun?',
      options: ['Blue', 'Green', 'Yellow', 'Red'],
      correctAnswer: 'Yellow',
    },
    {
      id: 14,
      question: 'How many fingers are in one hand?',
      options: ['4', '5', '6', '10'],
      correctAnswer: '5',
    },
    {
      id: 15,
      question: 'Which bird cannot fly?',
      options: ['Parrot', 'Crow', 'Penguin', 'Sparrow'],
      correctAnswer: 'Penguin',
    },
    {
      id: 16,
      question: 'What is 2 + 2?',
      options: ['3', '4', '5', '6'],
      correctAnswer: '4',
    },
    {
      id: 17,
      question: 'Which fruit is red and round?',
      options: ['Banana', 'Apple', 'Orange', 'Grapes'],
      correctAnswer: 'Apple',
    },
    {
      id: 18,
      question: 'What is the opposite of "big"?',
      options: ['Tall', 'Small', 'Large', 'Huge'],
      correctAnswer: 'Small',
    },
    {
      id: 19,
      question: 'Which sense do we use to see?',
      options: ['Hearing', 'Smell', 'Sight', 'Taste'],
      correctAnswer: 'Sight',
    },
    {
      id: 20,
      question: 'Which month has the least number of days?',
      options: ['January', 'February', 'March', 'April'],
      correctAnswer: 'February',
    },
    {
      id: 21,
      question: 'What is the color of grass?',
      options: ['Red', 'Yellow', 'Blue', 'Green'],
      correctAnswer: 'Green',
    },
    {
      id: 22,
      question: 'How many wheels does a bicycle have?',
      options: ['1', '2', '3', '4'],
      correctAnswer: '2',
    },
    {
      id: 23,
      question: 'Which animal gives us milk?',
      options: ['Dog', 'Cat', 'Cow', 'Goat'],
      correctAnswer: 'Cow',
    },
    {
      id: 24,
      question: 'What do you wear on your feet?',
      options: ['Hat', 'Gloves', 'Shoes', 'Scarf'],
      correctAnswer: 'Shoes',
    },
    {
      id: 25,
      question: 'What is the first letter of the alphabet?',
      options: ['A', 'B', 'C', 'Z'],
      correctAnswer: 'A',
    },
    {
      id: 26,
      question: 'Which animal says "meow"?',
      options: ['Dog', 'Cat', 'Bird', 'Cow'],
      correctAnswer: 'Cat',
    },
    {
      id: 27,
      question: 'Where does the sun rise from?',
      options: ['West', 'North', 'East', 'South'],
      correctAnswer: 'East',
    },
    {
      id: 28,
      question: 'How many colors are in a rainbow?',
      options: ['5', '6', '7', '8'],
      correctAnswer: '7',
    },
    {
      id: 29,
      question: 'What is the national bird of India?',
      options: ['Peacock', 'Sparrow', 'Pigeon', 'Crow'],
      correctAnswer: 'Peacock',
    },
    {
      id: 30,
      question: 'What is the baby of a cat called?',
      options: ['Puppy', 'Kitten', 'Chick', 'Cub'],
      correctAnswer: 'Kitten',
    },
    {
      id: 31,
      question: 'What is 5 - 3?',
      options: ['1', '2', '3', '4'],
      correctAnswer: '2',
    },
    {
      id: 32,
      question: 'Which planet is closest to the Sun?',
      options: ['Venus', 'Earth', 'Mercury', 'Mars'],
      correctAnswer: 'Mercury',
    },
    {
      id: 33,
      question: 'Which vehicle runs on a track?',
      options: ['Car', 'Bus', 'Train', 'Airplane'],
      correctAnswer: 'Train',
    },
    {
      id: 34,
      question: 'What is the color of the sky on a clear day?',
      options: ['Green', 'Blue', 'Red', 'Yellow'],
      correctAnswer: 'Blue',
    },
    {
      id: 35,
      question: 'What do plants need to grow?',
      options: ['Sunlight', 'Water', 'Soil', 'All of the above'],
      correctAnswer: 'All of the above',
    },
    {
      id: 36,
      question: 'How many legs does a spider have?',
      options: ['4', '6', '8', '10'],
      correctAnswer: '8',
    },
    {
      id: 37,
      question: 'Which fruit is the "king of fruits"?',
      options: ['Apple', 'Banana', 'Mango', 'Grapes'],
      correctAnswer: 'Mango',
    },
    {
      id: 38,
      question: 'Who was the first Prime Minister of India?',
      options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Indira Gandhi'],
      correctAnswer: 'Jawaharlal Nehru',
    },
    {
      id: 39,
      question: 'What is the largest animal on Earth?',
      options: ['Elephant', 'Blue Whale', 'Giraffe', 'Shark'],
      correctAnswer: 'Blue Whale',
    },
    {
      id: 40,
      question: 'What is the currency of India?',
      options: ['Dollar', 'Euro', 'Rupee', 'Yen'],
      correctAnswer: 'Rupee',
    },
    {
      id: 41,
      question: 'What is the main language spoken in India?',
      options: ['English', 'Hindi', 'Tamil', 'Bengali'],
      correctAnswer: 'Hindi',
    },
    {
      id: 42,
      question: 'The Taj Mahal is located in which city?',
      options: ['Delhi', 'Mumbai', 'Agra', 'Jaipur'],
      correctAnswer: 'Agra',
    },
    {
      id: 43,
      question: 'What is the number that comes after 9?',
      options: ['8', '10', '11', '12'],
      correctAnswer: '10',
    },
    {
      id: 44,
      question: 'How many states are there in India?',
      options: ['28', '29', '30', '31'],
      correctAnswer: '28',
    },
    {
      id: 45,
      question: 'What is the opposite of "hot"?',
      options: ['Warm', 'Cold', 'Spicy', 'Mild'],
      correctAnswer: 'Cold',
    },
    {
      id: 46,
      question: 'Which of these is a vegetable?',
      options: ['Apple', 'Carrot', 'Banana', 'Orange'],
      correctAnswer: 'Carrot',
    },
    {
      id: 47,
      question: 'Which animal has a long trunk?',
      options: ['Lion', 'Monkey', 'Elephant', 'Zebra'],
      correctAnswer: 'Elephant',
    },
    {
      id: 48,
      question: 'What do we use to write on a blackboard?',
      options: ['Pen', 'Pencil', 'Chalk', 'Crayon'],
      correctAnswer: 'Chalk',
    },
    {
      id: 49,
      question: 'Which day comes after Saturday?',
      options: ['Monday', 'Friday', 'Sunday', 'Tuesday'],
      correctAnswer: 'Sunday',
    },
    {
      id: 50,
      question: 'What is the young one of a sheep called?',
      options: ['Calf', 'Lamb', 'Foal', 'Piglet'],
      correctAnswer: 'Lamb',
    },
    {
      id: 51,
      question: 'Which shape has no sides?',
      options: ['Square', 'Triangle', 'Circle', 'Rectangle'],
      correctAnswer: 'Circle',
    },
    {
      id: 52,
      question: 'What is the home of a lion called?',
      options: ['Nest', 'Den', 'Burrow', 'Stable'],
      correctAnswer: 'Den',
    },
    {
      id: 53,
      question: 'Which is the tallest animal in the world?',
      options: ['Elephant', 'Giraffe', 'Camel', 'Horse'],
      correctAnswer: 'Giraffe',
    },
    {
      id: 54,
      question: 'What do we use to smell things?',
      options: ['Eyes', 'Ears', 'Nose', 'Tongue'],
      correctAnswer: 'Nose',
    },
    {
      id: 55,
      question: 'How many months are there in a year?',
      options: ['10', '11', '12', '13'],
      correctAnswer: '12',
    },
    {
      id: 56,
      question: 'What is the color of milk?',
      options: ['Red', 'Blue', 'White', 'Green'],
      correctAnswer: 'White',
    },
    {
      id: 57,
      question: 'What do we drink that comes from a cow?',
      options: ['Juice', 'Water', 'Milk', 'Soda'],
      correctAnswer: 'Milk',
    },
    {
      id: 58,
      question: 'Which festival is associated with Santa Claus?',
      options: ['Diwali', 'Holi', 'Eid', 'Christmas'],
      correctAnswer: 'Christmas',
    },
    {
      id: 59,
      question: 'How many primary colors are there?',
      options: ['2', '3', '4', '5'],
      correctAnswer: '3',
    },
    {
      id: 60,
      question: 'What is the national fruit of India?',
      options: ['Apple', 'Banana', 'Mango', 'Orange'],
      correctAnswer: 'Mango',
    },
    {
      id: 61,
      question: 'Which organ helps us to hear?',
      options: ['Eyes', 'Nose', 'Ears', 'Skin'],
      correctAnswer: 'Ears',
    },
    {
      id: 62,
      question: 'How many legs does a chair usually have?',
      options: ['2', '3', '4', '5'],
      correctAnswer: '4',
    },
    {
      id: 63,
      question: 'Which animal says "oink"?',
      options: ['Cow', 'Pig', 'Sheep', 'Duck'],
      correctAnswer: 'Pig',
    },
    {
      id: 64,
      question: 'Which of these is not a season?',
      options: ['Summer', 'Winter', 'Monday', 'Rainy'],
      correctAnswer: 'Monday',
    },
    {
      id: 65,
      question: 'Which planet do we live on?',
      options: ['Mars', 'Venus', 'Earth', 'Jupiter'],
      correctAnswer: 'Earth',
    },
    {
      id: 66,
      question: 'What is the opposite of "day"?',
      options: ['Morning', 'Evening', 'Night', 'Noon'],
      correctAnswer: 'Night',
    },
    {
      id: 67,
      question: 'Which direction does a compass point to?',
      options: ['South', 'East', 'West', 'North'],
      correctAnswer: 'North',
    },
    {
      id: 68,
      question: 'What is 10 + 5?',
      options: ['10', '15', '20', '25'],
      correctAnswer: '15',
    },
    {
      id: 69,
      question: 'What is the sound of a lion?',
      options: ['Bark', 'Roar', 'Moo', 'Chirp'],
      correctAnswer: 'Roar',
    },
    {
      id: 70,
      question: 'What is the national tree of India?',
      options: ['Banyan Tree', 'Neem Tree', 'Mango Tree', 'Peepal Tree'],
      correctAnswer: 'Banyan Tree',
    },
    {
      id: 71,
      question: 'What do you use to brush your teeth?',
      options: ['Soap', 'Shampoo', 'Toothbrush', 'Comb'],
      correctAnswer: 'Toothbrush',
    },
    {
      id: 72,
      question: 'Which number comes before 5?',
      options: ['3', '4', '6', '7'],
      correctAnswer: '4',
    },
    {
      id: 73,
      question: 'Which is the largest continent?',
      options: ['Africa', 'Europe', 'Asia', 'Australia'],
      correctAnswer: 'Asia',
    },
    {
      id: 74,
      question: 'What is the main source of light on Earth?',
      options: ['Moon', 'Stars', 'Sun', 'Bulb'],
      correctAnswer: 'Sun',
    },
    {
      id: 75,
      question: 'What is the shape of an egg?',
      options: ['Circle', 'Square', 'Oval', 'Triangle'],
      correctAnswer: 'Oval',
    },
    {
      id: 76,
      question: 'Which animal is called "man\'s best friend"?',
      options: ['Cat', 'Dog', 'Horse', 'Rabbit'],
      correctAnswer: 'Dog',
    },
    {
      id: 77,
      question: 'What is the capital of France?',
      options: ['London', 'Berlin', 'Paris', 'Rome'],
      correctAnswer: 'Paris',
    },
    {
      id: 78,
      question: 'What do bees give us?',
      options: ['Milk', 'Honey', 'Eggs', 'Wool'],
      correctAnswer: 'Honey',
    },
    {
      id: 79,
      question: 'Which of these is a reptile?',
      options: ['Fish', 'Bird', 'Snake', 'Monkey'],
      correctAnswer: 'Snake',
    },
    {
      id: 80,
      question: 'How many sides does a square have?',
      options: ['3', '4', '5', '6'],
      correctAnswer: '4',
    },
    {
      id: 81,
      question: 'Which tool is used to cut paper?',
      options: ['Hammer', 'Screwdriver', 'Scissors', 'Wrench'],
      correctAnswer: 'Scissors',
    },
    {
      id: 82,
      question: 'What is the top color in a rainbow?',
      options: ['Blue', 'Green', 'Yellow', 'Red'],
      correctAnswer: 'Red',
    },
    {
      id: 83,
      question: 'In which season do we wear sweaters?',
      options: ['Summer', 'Winter', 'Rainy', 'Spring'],
      correctAnswer: 'Winter',
    },
    {
      id: 84,
      question: 'What is the national game of India?',
      options: ['Cricket', 'Football', 'Hockey', 'Kabaddi'],
      correctAnswer: 'Hockey',
    },
    {
      id: 85,
      question: 'How many vowels are in the English alphabet?',
      options: ['4', '5', '6', '7'],
      correctAnswer: '5',
    },
    {
      id: 86,
      question: 'Which animal can live both on land and in water?',
      options: ['Fish', 'Frog', 'Lion', 'Goat'],
      correctAnswer: 'Frog',
    },
    {
      id: 87,
      question: 'What is the color of a banana?',
      options: ['Red', 'Green', 'Yellow', 'Blue'],
      correctAnswer: 'Yellow',
    },
    {
      id: 88,
      question: 'Which part of your body do you use to taste food?',
      options: ['Nose', 'Eyes', 'Ears', 'Tongue'],
      correctAnswer: 'Tongue',
    },
    {
      id: 89,
      question: 'Which monument is in Kolkata?',
      options: ['Taj Mahal', 'India Gate', 'Howrah Bridge', 'Charminar'],
      correctAnswer: 'Howrah Bridge',
    },
    {
      id: 90,
      question: 'What is 3 x 4?',
      options: ['7', '10', '12', '14'],
      correctAnswer: '12',
    },
  ],
  '5-7': [
    {
      id: 1,
      question: 'Which is heavier: 1 kg of cotton or 1 kg of iron?',
      options: ['Iron', 'Cotton', 'Both are equal', 'None'],
      correctAnswer: 'Both are equal',
    },
    {
      id: 2,
      question: 'Mohenjo-Daro is associated with which ancient civilization?',
      options: ['Egyptian', 'Mesopotamian', 'Indus Valley', 'Chinese'],
      correctAnswer: 'Indus Valley',
    },
    {
      id: 3,
      question: 'Sanchi Stupa is associated with which religion?',
      options: ['Jainism', 'Buddhism', 'Hinduism', 'Christianity'],
      correctAnswer: 'Buddhism',
    },
    {
      id: 4,
      question: 'Who wrote the Mahabharata?',
      options: ['Valmiki', 'Ved Vyas', 'Kalidasa', 'Chanakya'],
      correctAnswer: 'Ved Vyas',
    },
    {
      id: 5,
      question: 'Which is the largest organ in the human body?',
      options: ['Liver', 'Skin', 'Heart', 'Brain'],
      correctAnswer: 'Skin',
    },
    {
      id: 6,
      question: 'Who built the Red Fort in Delhi?',
      options: ['Akbar', 'Shah Jahan', 'Humayun', 'Aurangzeb'],
      correctAnswer: 'Shah Jahan',
    },
    {
      id: 7,
      question: 'Which country is the neighbor of India to the North?',
      options: ['Sri Lanka', 'China', 'Maldives', 'Myanmar'],
      correctAnswer: 'China',
    },
    {
      id: 8,
      question: 'The national song of India is?',
      options: ['Jana Gana Mana', 'Vande Mataram', 'Sare Jahan Se Achha', 'Mera Rang De Basanti'],
      correctAnswer: 'Vande Mataram',
    },
    {
      id: 9,
      question: 'Which number is smallest?',
      options: ['1/2', '2/3', '3/4', '1/3'],
      correctAnswer: '1/3',
    },
    {
      id: 10,
      question: 'A clock shows 3:15. What is the angle between hour and minute hands?',
      options: ['30°', '7.5°', '45°', '15°'],
      correctAnswer: '7.5°',
    },
    {
      id: 11,
      question: 'Which vitamin is produced by the human body in sunlight?',
      options: ['Vitamin A', 'Vitamin D', 'Vitamin C', 'Vitamin B12'],
      correctAnswer: 'Vitamin D',
    },
    {
      id: 12,
      question: 'Who is the current Chief Minister of Bihar (2025)?',
      options: ['Tejashwi Yadav', 'Nitish Kumar', 'Lalu Prasad Yadav', 'Jitan Ram Manjhi'],
      correctAnswer: 'Nitish Kumar',
    },
    {
      id: 13,
      question: 'Which part of the plant prepares food?',
      options: ['Root', 'Stem', 'Leaf', 'Flower'],
      correctAnswer: 'Leaf',
    },
    {
      id: 14,
      question: 'The Lotus Temple is located in?',
      options: ['Delhi', 'Mumbai', 'Kolkata', 'Hyderabad'],
      correctAnswer: 'Delhi',
    },
    {
      id: 15,
      question: '90 ÷ 9 = ?',
      options: ['9', '10', '8', '7'],
      correctAnswer: '10',
    },
    {
      id: 16,
      question: 'Which is odd one out: Square, Triangle, Circle, Rectangle?',
      options: ['Square', 'Triangle', 'Circle', 'Rectangle'],
      correctAnswer: 'Circle',
    },
    {
      id: 17,
      question: 'Which Indian airport is the busiest (by passenger traffic)?',
      options: ['Kolkata', 'Delhi', 'Mumbai', 'Bengaluru'],
      correctAnswer: 'Delhi',
    },
    {
      id: 18,
      question: 'If CAT = 24, then DOG = ? (A=1, B=2, … Z=26)',
      options: ['26', '28', '48', '38'],
      correctAnswer: '26',
    },
    {
      id: 19,
      question: "Which state recently launched 'Har Ghar Jal Yojana'?",
      options: ['Gujarat', 'Uttar Pradesh', 'Bihar', 'Haryana'],
      correctAnswer: 'Uttar Pradesh',
    },
    {
      id: 20,
      question: 'Which is the heaviest metal?',
      options: ['Gold', 'Lead', 'Osmium', 'Silver'],
      correctAnswer: 'Osmium',
    },
    {
      id: 21,
      question: 'Which cricketer became the first to score 100 international centuries?',
      options: ['Virat Kohli', 'Sachin Tendulkar', 'Rohit Sharma', 'M.S. Dhoni'],
      correctAnswer: 'Sachin Tendulkar',
    },
    {
      id: 22,
      question: 'Pongal is a harvest festival of which state?',
      options: ['Kerala', 'Tamil Nadu', 'Andhra Pradesh', 'Punjab'],
      correctAnswer: 'Tamil Nadu',
    },
    {
      id: 23,
      question: 'Which is the missing number: 3, 6, 12, 24, __ ?',
      options: ['36', '48', '54', '42'],
      correctAnswer: '48',
    },
    {
      id: 24,
      question: "Who is known as the 'Missile Man of India'?",
      options: ['Homi Bhabha', 'Vikram Sarabhai', 'A.P.J. Abdul Kalam', 'Rakesh Sharma'],
      correctAnswer: 'A.P.J. Abdul Kalam',
    },
    {
      id: 25,
      question: 'Holi is also called?',
      options: ['Festival of Flowers', 'Festival of Lights', 'Festival of Colours', 'Festival of Harvest'],
      correctAnswer: 'Festival of Colours',
    },
    {
      id: 26,
      question: 'Onam is the festival of which state?',
      options: ['Karnataka', 'Kerala', 'Assam', 'Gujarat'],
      correctAnswer: 'Kerala',
    },
    {
      id: 27,
      question: 'Which planet is known as the Red Planet?',
      options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
      correctAnswer: 'Mars',
    },
    {
      id: 28,
      question: 'Water boils at what temperature (at sea level)?',
      options: ['50°C', '100°C', '120°C', '80°C'],
      correctAnswer: '100°C',
    },
    {
      id: 29,
      question: 'If TODAY is coded as UPEBZ, then BOOK is coded as?',
      options: ['CPPL', 'DOOL', 'AONL', 'BPPL'],
      correctAnswer: 'CPPL',
    },
    {
      id: 30,
      question: 'Which is the fastest land animal?',
      options: ['Lion', 'Cheetah', 'Horse', 'Tiger'],
      correctAnswer: 'Cheetah',
    },
    {
      id: 31,
      question: 'Who is the current President of India (2025)?',
      options: ['Pratibha Patil', 'Ram Nath Kovind', 'Droupadi Murmu', 'Indira Gandhi'],
      correctAnswer: 'Droupadi Murmu',
    },
    {
      id: 32,
      question: 'What will be the day after 2 days of Monday?',
      options: ['Wednesday', 'Thursday', 'Friday', 'Saturday'],
      correctAnswer: 'Thursday',
    },
    {
      id: 33,
      question: 'The Ratha Yatra is most famous in which city?',
      options: ['Jaipur', 'Puri', 'Varanasi', 'Madurai'],
      correctAnswer: 'Puri',
    },
    {
      id: 34,
      question: 'Which player won the 2024 ICC Men’s T20 World Cup?',
      options: ['Australia', 'India', 'England', 'Pakistan'],
      correctAnswer: 'India',
    },
    {
      id: 35,
      question: 'Janmashtami celebrates the birth of which deity?',
      options: ['Rama', 'Krishna', 'Shiva', 'Vishnu'],
      correctAnswer: 'Krishna',
    },
    {
      id: 36,
      question: 'Which star is nearest to Earth?',
      options: ['North Star', 'Sun', 'Sirius', 'Alpha Centauri'],
      correctAnswer: 'Sun',
    },
    {
      id: 37,
      question: 'The Konark Sun Temple is located in which state?',
      options: ['Odisha', 'Madhya Pradesh', 'Rajasthan', 'Karnataka'],
      correctAnswer: 'Odisha',
    },
    {
      id: 38,
      question: 'Which river is considered the holiest in Hinduism?',
      options: ['Yamuna', 'Ganga', 'Godavari', 'Narmada'],
      correctAnswer: 'Ganga',
    },
    {
      id: 39,
      question: 'The process by which plants make food is called?',
      options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Germination'],
      correctAnswer: 'Photosynthesis',
    },
    {
      id: 40,
      question: 'Which organ pumps blood in the human body?',
      options: ['Brain', 'Heart', 'Lungs', 'Kidney'],
      correctAnswer: 'Heart',
    },
    {
      id: 41,
      question: 'The study of stars and planets is called?',
      options: ['Zoology', 'Astronomy', 'Astrology', 'Geology'],
      correctAnswer: 'Astronomy',
    },
    {
      id: 42,
      question: 'Who is known as the Nightingale of India?',
      options: ['Annie Besant', 'Indira Gandhi', 'Sarojini Naidu', 'Rani Lakshmi Bai'],
      correctAnswer: 'Sarojini Naidu',
    },
    {
      id: 43,
      question: 'If you arrange these in alphabetical order: Cat, Apple, Dog, Ball – which comes second?',
      options: ['Cat', 'Apple', 'Ball', 'Dog'],
      correctAnswer: 'Ball',
    },
    {
      id: 44,
      question: 'If 1=3, 2=6, 3=9, then 5=?',
      options: ['12', '15', '20', '18'],
      correctAnswer: '15',
    },
    {
      id: 45,
      question: 'Who composed India’s national anthem?',
      options: ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Sarojini Naidu', 'Lala Lajpat Rai'],
      correctAnswer: 'Rabindranath Tagore',
    },
    {
      id: 46,
      question: 'Which planet is the largest in the Solar System?',
      options: ['Earth', 'Jupiter', 'Saturn', 'Neptune'],
      correctAnswer: 'Jupiter',
    },
    {
      id: 47,
      question: 'Who is the current UN Secretary-General (2025)?',
      options: ['Ban Ki-moon', 'António Guterres', 'Kofi Annan', 'Michelle Bachelet'],
      correctAnswer: 'António Guterres',
    },
    {
      id: 48,
      question: 'Which country won the FIFA World Cup 2022?',
      options: ['France', 'Argentina', 'Brazil', 'Germany'],
      correctAnswer: 'Argentina',
    },
    {
      id: 49,
      question: "Which gas is known as 'Laughing Gas'?",
      options: ['Oxygen', 'Nitrous Oxide', 'Carbon dioxide', 'Methane'],
      correctAnswer: 'Nitrous Oxide',
    },
    {
      id: 50,
      question: '1, 4, 9, 16, 25, __ ?',
      options: ['36', '49', '64', '81'],
      correctAnswer: '36',
    },
    {
      id: 51,
      question: 'Human beings have how many chromosomes?',
      options: ['44', '46', '48', '42'],
      correctAnswer: '46',
    },
    {
      id: 52,
      question: 'Which instrument is Ustad Bismillah Khan famous for?',
      options: ['Veena', 'Sitar', 'Shehnai', 'Flute'],
      correctAnswer: 'Shehnai',
    },
    {
      id: 53,
      question: 'Which animal lays eggs?',
      options: ['Cat', 'Cow', 'Hen', 'Dog'],
      correctAnswer: 'Hen',
    },
    {
      id: 54,
      question: "Which festival is also called the 'festival of kites'?",
      options: ['Lohri', 'Makar Sankranti', 'Onam', 'Ugadi'],
      correctAnswer: 'Makar Sankranti',
    },
    {
      id: 55,
      question: 'Which shape has 5 sides?',
      options: ['Triangle', 'Square', 'Pentagon', 'Hexagon'],
      correctAnswer: 'Pentagon',
    },
    {
      id: 56,
      question: 'Who wrote the Ramayana?',
      options: ['Tulsidas', 'Valmiki', 'Ved Vyas', 'Kalidasa'],
      correctAnswer: 'Valmiki',
    },
    {
      id: 57,
      question: 'Which gas do humans inhale to survive?',
      options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'],
      correctAnswer: 'Oxygen',
    },
    {
      id: 58,
      question: 'Which company is India’s largest IT services firm?',
      options: ['Infosys', 'TCS', 'Wipro', 'HCL'],
      correctAnswer: 'TCS',
    },
    {
      id: 59,
      question: 'A cube has how many faces?',
      options: ['6', '8', '10', '12'],
      correctAnswer: '6',
    },
    {
      id: 60,
      question: 'If 5 pencils cost ₹25, how much will 10 pencils cost?',
      options: ['₹50', '₹30', '₹40', '₹45'],
      correctAnswer: '₹50',
    },
    {
      id: 61,
      question: "Who is known as the 'Father of the Nation' in India?",
      options: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel', 'Subhash Chandra Bose'],
      correctAnswer: 'Mahatma Gandhi',
    },
    {
      id: 62,
      question: 'Kathak dance originated in which part of India?',
      options: ['North India', 'South India', 'West India', 'East India'],
      correctAnswer: 'North India',
    },
    {
      id: 63,
      question: 'Which blood group is known as the universal donor?',
      options: ['A', 'B', 'O negative', 'AB positive'],
      correctAnswer: 'O negative',
    },
    {
      id: 64,
      question: "Which part of the human body is called the 'control center'?",
      options: ['Lungs', 'Brain', 'Heart', 'Kidney'],
      correctAnswer: 'Brain',
    },
    {
      id: 65,
      question: 'Which Indian state is the largest tea producer?',
      options: ['West Bengal', 'Assam', 'Kerala', 'Karnataka'],
      correctAnswer: 'Assam',
    },
    {
      id: 66,
      question: 'If 12 × 12 = 144, then 13 × 13 = ?',
      options: ['156', '169', '121', '143'],
      correctAnswer: '169',
    },
    {
      id: 67,
      question: "Which planet is called the 'Morning Star'?",
      options: ['Venus', 'Mercury', 'Mars', 'Saturn'],
      correctAnswer: 'Venus',
    },
    {
      id: 68,
      question: 'The festival of lights is known as?',
      options: ['Holi', 'Raksha Bandhan', 'Diwali', 'Eid'],
      correctAnswer: 'Diwali',
    },
    {
      id: 69,
      question: 'Which number comes next: 2, 4, 8, 16, __ ?',
      options: ['20', '24', '32', '18'],
      correctAnswer: '32',
    },
    {
      id: 70,
      question: 'Which gas is used by plants during photosynthesis?',
      options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
      correctAnswer: 'Carbon dioxide',
    },
    {
      id: 71,
      question: 'Which is India’s fastest train (2025)?',
      options: ['Rajdhani Express', 'Vande Bharat Express', 'Shatabdi Express', 'Duronto Express'],
      correctAnswer: 'Vande Bharat Express',
    },
    {
      id: 72,
      question: 'Find the odd one out: Mango, Banana, Apple, Carrot.',
      options: ['Mango', 'Banana', 'Apple', 'Carrot'],
      correctAnswer: 'Carrot',
    },
    {
      id: 73,
      question: 'Which energy is obtained from the Sun?',
      options: ['Nuclear', 'Solar', 'Hydro', 'Wind'],
      correctAnswer: 'Solar',
    },
    {
      id: 74,
      question: 'The Statue of Unity is dedicated to?',
      options: ['Mahatma Gandhi', 'Sardar Vallabhbhai Patel', 'Jawaharlal Nehru', 'Bhagat Singh'],
      correctAnswer: 'Sardar Vallabhbhai Patel',
    },
    {
      id: 75,
      question: 'Bharatnatyam is a classical dance form from which state?',
      options: ['Odisha', 'Tamil Nadu', 'Kerala', 'West Bengal'],
      correctAnswer: 'Tamil Nadu',
    },
    {
      id: 76,
      question: 'If 1 hour = 60 minutes, then 3 hours = ?',
      options: ['100 minutes', '120 minutes', '150 minutes', '180 minutes'],
      correctAnswer: '180 minutes',
    },
    {
      id: 77,
      question: 'Which is the G20 presidency host country for 2023?',
      options: ['India', 'USA', 'Brazil', 'Indonesia'],
      correctAnswer: 'India',
    },
    {
      id: 78,
      question: 'Which metal is liquid at room temperature?',
      options: ['Iron', 'Mercury', 'Aluminium', 'Copper'],
      correctAnswer: 'Mercury',
    },
    {
      id: 79,
      question: "Which state is called the 'Rice Bowl of India'?",
      options: ['Kerala', 'Punjab', 'Andhra Pradesh', 'West Bengal'],
      correctAnswer: 'Andhra Pradesh',
    },
    {
      id: 80,
      question: 'What is 25% of 200?',
      options: ['25', '40', '50', '75'],
      correctAnswer: '50',
    },
    {
      id: 81,
      question: 'Chandrayaan-3 mission was launched by which organization?',
      options: ['NASA', 'ISRO', 'DRDO', 'SpaceX'],
      correctAnswer: 'ISRO',
    },
    {
      id: 82,
      question: 'Who is the current Prime Minister of India (2025)?',
      options: ['Rahul Gandhi', 'Narendra Modi', 'Arvind Kejriwal', 'Amit Shah'],
      correctAnswer: 'Narendra Modi',
    },
    {
      id: 83,
      question: "'Satyameva Jayate' is taken from which text?",
      options: ['Rigveda', 'Mundaka Upanishad', 'Mahabharata', 'Ramayana'],
      correctAnswer: 'Mundaka Upanishad',
    },
    {
      id: 84,
      question: 'Which is the smallest bone in the human body?',
      options: ['Femur', 'Stapes', 'Tibia', 'Humerus'],
      correctAnswer: 'Stapes',
    },
    {
      id: 85,
      question: 'Which planet has rings around it?',
      options: ['Earth', 'Saturn', 'Venus', 'Mars'],
      correctAnswer: 'Saturn',
    },
    {
      id: 86,
      question: 'The Jallianwala Bagh massacre took place in which city?',
      options: ['Lucknow', 'Amritsar', 'Delhi', 'Kanpur'],
      correctAnswer: 'Amritsar',
    },
    {
      id: 87,
      question: 'In which city were the 2024 Summer Olympics held?',
      options: ['Tokyo', 'Paris', 'Beijing', 'London'],
      correctAnswer: 'Paris',
    },
    {
      id: 88,
      question: 'In which state is the Ajanta-Ellora caves?',
      options: ['Gujarat', 'Maharashtra', 'Karnataka', 'Odisha'],
      correctAnswer: 'Maharashtra',
    },
    {
      id: 89,
      question: "Which Indian city is known as 'Pink City'?",
      options: ['Udaipur', 'Jaipur', 'Jodhpur', 'Bikaner'],
      correctAnswer: 'Jaipur',
    },
    {
      id: 90,
      question: 'Earth revolves around the sun in how many days?',
      options: ['365', '360', '366', '364'],
      correctAnswer: '365',
    },
  ],
  '8-10': [
    {
      id: 1,
      question: 'Which Mughal ruler built Fatehpur Sikri?',
      options: ['Akbar', 'Humayun', 'Shah Jahan', 'Jahangir'],
      correctAnswer: 'Akbar',
    },
    {
      id: 2,
      question: 'Which country hosted the COP28 climate conference in 2023?',
      options: ['India', 'UAE', 'USA', 'UK'],
      correctAnswer: 'UAE',
    },
    {
      id: 3,
      question: 'India’s first bullet train project is between which two cities?',
      options: [
        'Delhi and Jaipur',
        'Mumbai and Ahmedabad',
        'Chennai and Bengaluru',
        'Kolkata and Patna',
      ],
      correctAnswer: 'Mumbai and Ahmedabad',
    },
    {
      id: 4,
      question: 'The Meenakshi Temple is located in?',
      options: ['Tamil Nadu', 'Kerala', 'Maharashtra', 'Andhra Pradesh'],
      correctAnswer: 'Tamil Nadu',
    },
    {
      id: 5,
      question:
        "Which law states that 'For every action there is an equal and opposite reaction'?",
      options: [
        'Newton’s First Law',
        'Newton’s Second Law',
        'Newton’s Third Law',
        'Law of Gravitation',
      ],
      correctAnswer: 'Newton’s Third Law',
    },
    {
      id: 6,
      question: 'Who was the founder of the Maurya Empire?',
      options: ['Chandragupta Maurya', 'Ashoka', 'Bindusara', 'Bimbisara'],
      correctAnswer: 'Chandragupta Maurya',
    },
    {
      id: 7,
      question: 'If the sum of two numbers is 60 and one number is twice the other, what are the numbers?',
      options: ['20 and 40', '15 and 45', '10 and 50', '25 and 35'],
      correctAnswer: '20 and 40',
    },
    {
      id: 8,
      question: 'Which metal is most reactive?',
      options: ['Iron', 'Sodium', 'Copper', 'Gold'],
      correctAnswer: 'Sodium',
    },
    {
      id: 9,
      question: 'India successfully landed Chandrayaan-3 on which part of the Moon?',
      options: ['Equator', 'South Pole', 'North Pole', 'Sea of Tranquility'],
      correctAnswer: 'South Pole',
    },
    {
      id: 10,
      question: 'If 5 men take 20 days to build a wall, how many days will 10 men take?',
      options: ['15', '20', '10', '5'],
      correctAnswer: '10',
    },
    {
      id: 11,
      question: 'Which is odd one out: Pentagon, Hexagon, Octagon, Circle?',
      options: ['Pentagon', 'Hexagon', 'Octagon', 'Circle'],
      correctAnswer: 'Circle',
    },
    {
      id: 12,
      question: 'Which text is considered the first grammar of Sanskrit?',
      options: [
        'Rigveda',
        'Ashtadhyayi by Panini',
        'Arthashastra',
        'Mahabharata',
      ],
      correctAnswer: 'Ashtadhyayi by Panini',
    },
    {
      id: 13,
      question: 'The SI unit of electric current is?',
      options: ['Watt', 'Ampere', 'Volt', 'Ohm'],
      correctAnswer: 'Ampere',
    },
    {
      id: 14,
      question: 'Which gas causes the greenhouse effect the most?',
      options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
      correctAnswer: 'Carbon dioxide',
    },
    {
      id: 15,
      question: 'Who won the Nobel Peace Prize in 2024?',
      options: ['Greta Thunberg', 'Narges Mohammadi', 'Malala Yousafzai', 'Abiy Ahmed'],
      correctAnswer: 'Narges Mohammadi',
    },
    {
      id: 16,
      question: "Which part of the cell is known as the 'powerhouse'?",
      options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Cytoplasm'],
      correctAnswer: 'Mitochondria',
    },
    {
      id: 17,
      question: 'Who built the Qutub Minar?',
      options: ['Akbar', 'Qutub-ud-din Aibak', 'Shah Jahan', 'Aurangzeb'],
      correctAnswer: 'Qutub-ud-din Aibak',
    },
    {
      id: 18,
      question: 'Find the missing number: 7, 14, 28, 56, __ ?',
      options: ['84', '100', '112', '64'],
      correctAnswer: '112',
    },
    {
      id: 19,
      question: 'Who is the current Chief Justice of India (2025)?',
      options: ['N.V. Ramana', 'D.Y. Chandrachud', 'Ranjan Gogoi', 'U.U. Lalit'],
      correctAnswer: 'D.Y. Chandrachud',
    },
    {
      id: 20,
      question: 'If EARTH is coded as UBGZI, then MOON is coded as?',
      options: ['NPPM', 'NLLO', 'ZBBM', 'ZOOM'],
      correctAnswer: 'ZBBM',
    },
    {
      id: 21,
      question: 'What is the chemical formula for water?',
      options: ['O2', 'H2O', 'CO2', 'NaCl'],
      correctAnswer: 'H2O',
    },
    {
      id: 22,
      question: 'The Quit India Movement was launched in which year?',
      options: ['1930', '1942', '1945', '1947'],
      correctAnswer: '1942',
    },
    {
      id: 23,
      question: 'What is the powerhouse of the cell?',
      options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'],
      correctAnswer: 'Mitochondria',
    },
    {
      id: 24,
      question: 'Which of the following is not a primary color?',
      options: ['Red', 'Yellow', 'Blue', 'Green'],
      correctAnswer: 'Green',
    },
    {
      id: 25,
      question: 'Who discovered penicillin?',
      options: ['Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Isaac Newton'],
      correctAnswer: 'Alexander Fleming',
    },
    {
      id: 26,
      question: 'The theory of relativity was proposed by?',
      options: ['Galileo Galilei', 'Isaac Newton', 'Albert Einstein', 'Stephen Hawking'],
      correctAnswer: 'Albert Einstein',
    },
    {
      id: 27,
      question: 'What is the largest bone in the human body?',
      options: ['Stapes', 'Femur', 'Tibia', 'Humerus'],
      correctAnswer: 'Femur',
    },
    {
      id: 28,
      question: 'Which Indian state is known as the "Land of Five Rivers"?',
      options: ['Haryana', 'Punjab', 'Gujarat', 'Rajasthan'],
      correctAnswer: 'Punjab',
    },
    {
      id: 29,
      question: 'What is the capital of Japan?',
      options: ['Beijing', 'Seoul', 'Tokyo', 'Bangkok'],
      correctAnswer: 'Tokyo',
    },
    {
      id: 30,
      question: 'Who wrote "Romeo and Juliet"?',
      options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
      correctAnswer: 'William Shakespeare',
    },
    {
      id: 31,
      question: 'What is the square root of 144?',
      options: ['10', '11', '12', '13'],
      correctAnswer: '12',
    },
    {
      id: 32,
      question: 'Which amendment of the Indian Constitution is known as the "Mini-Constitution"?',
      options: ['42nd Amendment', '44th Amendment', '1st Amendment', '73rd Amendment'],
      correctAnswer: '42nd Amendment',
    },
    {
      id: 33,
      question: 'The Battle of Plassey was fought in which year?',
      options: ['1757', '1764', '1857', '1776'],
      correctAnswer: '1757',
    },
    {
      id: 34,
      question: 'What does CPU stand for?',
      options: ['Central Processing Unit', 'Central Program Unit', 'Computer Personal Unit', 'Central Processor Unit'],
      correctAnswer: 'Central Processing Unit',
    },
    {
      id: 35,
      question: 'Which is the longest river in the world?',
      options: ['Amazon', 'Nile', 'Yangtze', 'Ganga'],
      correctAnswer: 'Nile',
    },
    {
      id: 36,
      question: 'The study of earthquakes is called?',
      options: ['Geology', 'Seismology', 'Volcanology', 'Meteorology'],
      correctAnswer: 'Seismology',
    },
    {
      id: 37,
      question: 'Who was the first woman Prime Minister of India?',
      options: ['Sarojini Naidu', 'Indira Gandhi', 'Sonia Gandhi', 'Pratibha Patil'],
      correctAnswer: 'Indira Gandhi',
    },
    {
      id: 38,
      question: 'Which element is essential for bone health?',
      options: ['Iron', 'Calcium', 'Potassium', 'Sodium'],
      correctAnswer: 'Calcium',
    },
    {
      id: 39,
      question: 'What is the chemical symbol for gold?',
      options: ['Ag', 'Au', 'Gd', 'Go'],
      correctAnswer: 'Au',
    },
    {
      id: 40,
      question: 'The headquarters of the United Nations is located in?',
      options: ['Geneva', 'Paris', 'New York', 'London'],
      correctAnswer: 'New York',
    },
    {
      id: 41,
      question: 'Who invented the light bulb?',
      options: ['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'James Watt'],
      correctAnswer: 'Thomas Edison',
    },
    {
      id: 42,
      question: 'A polygon with eight sides is called an?',
      options: ['Hexagon', 'Pentagon', 'Octagon', 'Decagon'],
      correctAnswer: 'Octagon',
    },
    {
      id: 43,
      question: 'Which Vitamin deficiency causes scurvy?',
      options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
      correctAnswer: 'Vitamin C',
    },
    {
      id: 44,
      question: 'Who is the author of "The Discovery of India"?',
      options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Rabindranath Tagore'],
      correctAnswer: 'Jawaharlal Nehru',
    },
    {
      id: 45,
      question: 'The pH of pure water is?',
      options: ['6', '7', '8', '9'],
      correctAnswer: '7',
    },
    {
      id: 46,
      question: 'Which country is known as the "Land of the Rising Sun"?',
      options: ['China', 'Japan', 'South Korea', 'Thailand'],
      correctAnswer: 'Japan',
    },
    {
      id: 47,
      question: 'What is the full form of ISRO?',
      options: ['Indian Space Research Organisation', 'International Space Research Organisation', 'Indian Satellite Research Organisation', 'Internal Space Research Organisation'],
      correctAnswer: 'Indian Space Research Organisation',
    },
    {
      id: 48,
      question: 'Which of these is a greenhouse gas?',
      options: ['Oxygen', 'Nitrogen', 'Methane', 'Hydrogen'],
      correctAnswer: 'Methane',
    },
    {
      id: 49,
      question: 'The Rajya Sabha is also known as?',
      options: ['Council of States', 'House of the People', 'Legislative Assembly', 'Parliament House'],
      correctAnswer: 'Council of States',
    },
    {
      id: 50,
      question: 'What is the hardest natural substance on Earth?',
      options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
      correctAnswer: 'Diamond',
    },
    {
      id: 51,
      question: 'Which instrument is used to measure blood pressure?',
      options: ['Thermometer', 'Barometer', 'Sphygmomanometer', 'Stethoscope'],
      correctAnswer: 'Sphygmomanometer',
    },
    {
      id: 52,
      question: 'Who was the first Indian to go to space?',
      options: ['Kalpana Chawla', 'Sunita Williams', 'Rakesh Sharma', 'Vikram Sarabhai'],
      correctAnswer: 'Rakesh Sharma',
    },
    {
      id: 53,
      question: 'What is the study of plants called?',
      options: ['Zoology', 'Botany', 'Geology', 'Ecology'],
      correctAnswer: 'Botany',
    },
    {
      id: 54,
      question: 'Which is the largest ocean in the world?',
      options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
      correctAnswer: 'Pacific Ocean',
    },
    {
      id: 55,
      question: 'The device used to convert AC to DC is called a?',
      options: ['Generator', 'Inverter', 'Rectifier', 'Transformer'],
      correctAnswer: 'Rectifier',
    },
    {
      id: 56,
      question: 'Who founded the Sikh religion?',
      options: ['Guru Gobind Singh', 'Guru Nanak Dev', 'Guru Arjan Dev', 'Guru Tegh Bahadur'],
      correctAnswer: 'Guru Nanak Dev',
    },
    {
      id: 57,
      question: 'What is the main component of natural gas?',
      options: ['Butane', 'Propane', 'Methane', 'Ethane'],
      correctAnswer: 'Methane',
    },
    {
      id: 58,
      question: 'The Indus Valley Civilization flourished on the banks of which river?',
      options: ['Ganges', 'Indus', 'Yamuna', 'Brahmaputra'],
      correctAnswer: 'Indus',
    },
    {
      id: 59,
      question: 'Which of the following is a non-renewable source of energy?',
      options: ['Solar', 'Wind', 'Coal', 'Tidal'],
      correctAnswer: 'Coal',
    },
    {
      id: 60,
      question: 'The "Dandi March" is associated with?',
      options: ['Salt Satyagraha', 'Quit India Movement', 'Non-Cooperation Movement', 'Civil Disobedience Movement'],
      correctAnswer: 'Salt Satyagraha',
    },
    {
      id: 61,
      question: 'Which planet is known for its Great Red Spot?',
      options: ['Mars', 'Jupiter', 'Saturn', 'Venus'],
      correctAnswer: 'Jupiter',
    },
    {
      id: 62,
      question: 'What is the chemical formula for common salt?',
      options: ['KCl', 'NaCl', 'CaCl2', 'MgCl2'],
      correctAnswer: 'NaCl',
    },
    {
      id: 63,
      question: 'Who was the last Mughal emperor?',
      options: ['Aurangzeb', 'Shah Jahan', 'Bahadur Shah Zafar', 'Akbar II'],
      correctAnswer: 'Bahadur Shah Zafar',
    },
    {
      id: 64,
      question: 'The phenomenon of light bending as it passes from one medium to another is called?',
      options: ['Reflection', 'Refraction', 'Diffraction', 'Dispersion'],
      correctAnswer: 'Refraction',
    },
    {
      id: 65,
      question: 'Which acid is found in lemon?',
      options: ['Acetic acid', 'Citric acid', 'Lactic acid', 'Formic acid'],
      correctAnswer: 'Citric acid',
    },
    {
      id: 66,
      question: 'Who is known as the "Father of the Indian Constitution"?',
      options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Dr. B.R. Ambedkar', 'Sardar Patel'],
      correctAnswer: 'Dr. B.R. Ambedkar',
    },
    {
      id: 67,
      question: 'What is the boiling point of water in Fahrenheit?',
      options: ['100°F', '212°F', '32°F', '0°F'],
      correctAnswer: '212°F',
    },
    {
      id: 68,
      question: 'Which country won the first FIFA World Cup in 1930?',
      options: ['Argentina', 'Brazil', 'Uruguay', 'Italy'],
      correctAnswer: 'Uruguay',
    },
    {
      id: 69,
      question: 'The instrument used to measure the purity of milk is?',
      options: ['Hygrometer', 'Lactometer', 'Barometer', 'Amperemeter'],
      correctAnswer: 'Lactometer',
    },
    {
      id: 70,
      question: 'The deficiency of which hormone causes diabetes?',
      options: ['Thyroxine', 'Insulin', 'Adrenaline', 'Estrogen'],
      correctAnswer: 'Insulin',
    },
    {
      id: 71,
      question: 'Which is the highest peak in the world?',
      options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'],
      correctAnswer: 'Mount Everest',
    },
    {
      id: 72,
      question: 'Who wrote the national anthem of Bangladesh, "Amar Shonar Bangla"?',
      options: ['Kazi Nazrul Islam', 'Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Jasimuddin'],
      correctAnswer: 'Rabindranath Tagore',
    },
    {
      id: 73,
      question: "What is the main cause of tides in the ocean?",
      options: ["Earth's rotation", 'Wind', "Moon's gravitational pull", "Sun's heat"],
      correctAnswer: "Moon's gravitational pull",
    },
    {
      id: 74,
      question: 'Which state has the longest coastline in India?',
      options: ['Maharashtra', 'Kerala', 'Gujarat', 'Tamil Nadu'],
      correctAnswer: 'Gujarat',
    },
    {
      id: 75,
      question: 'What is the speed of light in a vacuum?',
      options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'],
      correctAnswer: '300,000 km/s',
    },
    {
      id: 76,
      question: 'The first battle of Panipat was fought between?',
      options: ['Akbar and Hemu', 'Babar and Ibrahim Lodi', 'Humayun and Sher Shah Suri', 'Akbar and Rana Pratap'],
      correctAnswer: 'Babar and Ibrahim Lodi',
    },
    {
      id: 77,
      question: 'Which of these is an input device for a computer?',
      options: ['Monitor', 'Printer', 'Speaker', 'Mouse'],
      correctAnswer: 'Mouse',
    },
    {
      id: 78,
      question: 'The study of fungi is known as?',
      options: ['Mycology', 'Phycology', 'Virology', 'Bacteriology'],
      correctAnswer: 'Mycology',
    },
    {
      id: 79,
      question: 'Which gland is known as the "master gland"?',
      options: ['Thyroid gland', 'Adrenal gland', 'Pituitary gland', 'Pancreas'],
      correctAnswer: 'Pituitary gland',
    },
    {
      id: 80,
      question: 'Who was the first woman to win a Nobel Prize?',
      options: ['Mother Teresa', 'Marie Curie', 'Rosalind Franklin', 'Dorothy Hodgkin'],
      correctAnswer: 'Marie Curie',
    },
    {
      id: 81,
      question: "Which gas is most abundant in the Earth's atmosphere?",
      options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'],
      correctAnswer: 'Nitrogen',
    },
    {
      id: 82,
      question: 'The "Silicon Valley of India" refers to which city?',
      options: ['Hyderabad', 'Pune', 'Bengaluru', 'Chennai'],
      correctAnswer: 'Bengaluru',
    },
    {
      id: 83,
      question: 'What does "www" stand for in a website address?',
      options: ['World Wide Web', 'World Web Wide', 'Web World Wide', 'Wide World Web'],
      correctAnswer: 'World Wide Web',
    },
    {
      id: 84,
      question: 'Which country is the largest producer of coffee in the world?',
      options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'],
      correctAnswer: 'Brazil',
    },
    {
      id: 85,
      question: 'The Suez Canal connects which two seas?',
      options: ['Red Sea and Black Sea', 'Mediterranean Sea and Red Sea', 'Baltic Sea and North Sea', 'Arabian Sea and Bay of Bengal'],
      correctAnswer: 'Mediterranean Sea and Red Sea',
    },
    {
      id: 86,
      question: 'What is the process of converting a solid directly into a gas called?',
      options: ['Evaporation', 'Condensation', 'Sublimation', 'Melting'],
      correctAnswer: 'Sublimation',
    },
    {
      id: 87,
      question: 'Who was the first President of India?',
      options: ['Dr. Rajendra Prasad', 'S. Radhakrishnan', 'Jawaharlal Nehru', 'Zakir Husain'],
      correctAnswer: 'Dr. Rajendra Prasad',
    },
    {
      id: 88,
      question: 'The Great Wall of China was built to protect against invasions from the?',
      options: ['South', 'East', 'West', 'North'],
      correctAnswer: 'North',
    },
    {
      id: 89,
      question: 'Which is the largest desert in the world?',
      options: ['Sahara Desert', 'Gobi Desert', 'Antarctic Polar Desert', 'Arabian Desert'],
      correctAnswer: 'Antarctic Polar Desert',
    },
    {
      id: 90,
      question: 'What is the value of Pi (π) up to two decimal places?',
      options: ['3.12', '3.14', '3.16', '3.18'],
      correctAnswer: '3.14',
    },
  ],
  '11-12': [
    {
      id: 1,
      question: 'Which country won the ICC Cricket World Cup 2023?',
      options: ['India', 'Australia', 'England', 'Pakistan'],
      correctAnswer: 'Australia',
    },
    {
      id: 2,
      question: "Who composed the epic 'Meghaduta'?",
      options: ['Tulsidas', 'Kalidasa', 'Valmiki', 'Kabir'],
      correctAnswer: 'Kalidasa',
    },
    {
      id: 3,
      question: 'Ellora caves are famous for?',
      options: ['Paintings', 'Stupas', 'Rock-cut temples', 'Pillars'],
      correctAnswer: 'Rock-cut temples',
    },
    {
      id: 4,
      question: "Who wrote the book 'Arthashastra'?",
      options: ['Chanakya', 'Kalidasa', 'Banabhatta', 'Aryabhata'],
      correctAnswer: 'Chanakya',
    },
    {
      id: 5,
      question: 'If 3 pencils cost ₹15, how much will 7 pencils cost?',
      options: ['₹30', '₹25', '₹35', '₹40'],
      correctAnswer: '₹35',
    },
    {
      id: 6,
      question: 'The functional unit of the kidney is?',
      options: ['Neuron', 'Nephron', 'Alveoli', 'Glomerulus'],
      correctAnswer: 'Nephron',
    },
    {
      id: 7,
      question: 'Which organelle is responsible for photosynthesis?',
      options: ['Mitochondria', 'Ribosome', 'Chloroplast', 'Nucleus'],
      correctAnswer: 'Chloroplast',
    },
    {
      id: 8,
      question: 'Find the next number in the series: 2, 6, 12, 20, ?',
      options: ['28', '30', '32', '34'],
      correctAnswer: '30',
    },
    {
      id: 9,
      question: 'Who is the current UN Secretary-General (2025)?',
      options: ['Ban Ki-moon', 'Antonio Guterres', 'Kofi Annan', 'Michelle Bachelet'],
      correctAnswer: 'Antonio Guterres',
    },
    {
      id: 10,
      question: 'Who was the founder of the Gupta dynasty?',
      options: ['Chandragupta I', 'Samudragupta', 'Ashoka', 'Kumaragupta'],
      correctAnswer: 'Chandragupta I',
    },
    {
      id: 11,
      question: 'Which element has the highest electronegativity?',
      options: ['Oxygen', 'Fluorine', 'Chlorine', 'Nitrogen'],
      correctAnswer: 'Fluorine',
    },
    {
      id: 12,
      question: 'If A is older than B, and B is older than C, who is the youngest?',
      options: ['A', 'B', 'C', 'Cannot determine'],
      correctAnswer: 'C',
    },
    {
      id: 13,
      question: 'Which mission did ISRO launch in 2024 for studying the Sun?',
      options: ['Aditya-L1', 'Chandrayaan-3', 'Mangalyaan-2', 'Gaganyaan'],
      correctAnswer: 'Aditya-L1',
    },
    {
      id: 14,
      question: 'Which Indian city was declared a UNESCO World Heritage City?',
      options: ['Jaipur', 'Ahmedabad', 'Delhi', 'Varanasi'],
      correctAnswer: 'Ahmedabad',
    },
    {
      id: 15,
      question: 'Who is the current Prime Minister of India (2025)?',
      options: ['Narendra Modi', 'Rahul Gandhi', 'Amit Shah', 'Arvind Kejriwal'],
      correctAnswer: 'Narendra Modi',
    },
    {
      id: 16,
      question: 'The rate of change of momentum is equal to?',
      options: ['Force', 'Energy', 'Work', 'Power'],
      correctAnswer: 'Force',
    },
    {
      id: 17,
      question: 'Which law explains the relationship between pressure and volume of a gas?',
      options: ['Boyle’s Law', 'Charles’ Law', 'Avogadro’s Law', 'Dalton’s Law'],
      correctAnswer: 'Boyle’s Law',
    },
    {
      id: 18,
      question: 'Bharatanatyam is a dance form from which state?',
      options: ['Kerala', 'Tamil Nadu', 'Odisha', 'Karnataka'],
      correctAnswer: 'Tamil Nadu',
    },
    {
      id: 19,
      question: 'Which is the odd one out: Iron, Copper, Aluminium, Plastic?',
      options: ['Iron', 'Copper', 'Aluminium', 'Plastic'],
      correctAnswer: 'Plastic',
    },
    {
      id: 20,
      question: 'If CLOCK = DMPDL, then WATCH = ?',
      options: ['XBUCI', 'XBUDI', 'XBVCH', 'XBVCI'],
      correctAnswer: 'XBUDI',
    },
    {
      id: 21,
      question: 'What is the escape velocity of Earth?',
      options: ['9.8 km/s', '11.2 km/s', '15.5 km/s', '20.1 km/s'],
      correctAnswer: '11.2 km/s',
    },
    {
      id: 22,
      question: 'The concept of "zero" was invented in which country?',
      options: ['Greece', 'Egypt', 'India', 'China'],
      correctAnswer: 'India',
    },
    {
      id: 23,
      question: 'Which is the largest gland in the human body?',
      options: ['Pancreas', 'Liver', 'Thyroid', 'Adrenal'],
      correctAnswer: 'Liver',
    },
    {
      id: 24,
      question: "The 'Permanent Settlement' of Bengal was introduced by?",
      options: ['Lord Cornwallis', 'Warren Hastings', 'Lord Wellesley', 'Robert Clive'],
      correctAnswer: 'Lord Cornwallis',
    },
    {
      id: 25,
      question: 'Which of the following is a vector quantity?',
      options: ['Speed', 'Mass', 'Time', 'Velocity'],
      correctAnswer: 'Velocity',
    },
    {
      id: 26,
      question: 'The "Doppler effect" is associated with?',
      options: ['Sound', 'Light', 'Both Sound and Light', 'Magnetism'],
      correctAnswer: 'Both Sound and Light',
    },
    {
      id: 27,
      question: 'What is the primary function of DNA?',
      options: ['Protein synthesis', 'Energy storage', 'Storing genetic information', 'Cellular transport'],
      correctAnswer: 'Storing genetic information',
    },
    {
      id: 28,
      question: 'Which article of the Indian Constitution deals with the Right to Equality?',
      options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'],
      correctAnswer: 'Article 14',
    },
    {
      id: 29,
      question: 'The process of splitting of a heavy nucleus into two lighter nuclei is called?',
      options: ['Nuclear Fusion', 'Nuclear Fission', 'Chain Reaction', 'Radioactivity'],
      correctAnswer: 'Nuclear Fission',
    },
    {
      id: 30,
      question: 'Who is known as the "Father of Economics"?',
      options: ['John Maynard Keynes', 'Karl Marx', 'Adam Smith', 'Milton Friedman'],
      correctAnswer: 'Adam Smith',
    },
    {
      id: 31,
      question: 'Which type of lens is used to correct myopia (nearsightedness)?',
      options: ['Convex lens', 'Concave lens', 'Bifocal lens', 'Cylindrical lens'],
      correctAnswer: 'Concave lens',
    },
    {
      id: 32,
      question: 'The "Green Revolution" in India was primarily associated with the production of?',
      options: ['Rice', 'Wheat', 'Pulses', 'Milk'],
      correctAnswer: 'Wheat',
    },
    {
      id: 33,
      question: 'What is the full form of GST in the Indian tax system?',
      options: ['General Sales Tax', 'Goods and Services Tax', 'Government Sales Tax', 'General Service Tax'],
      correctAnswer: 'Goods and Services Tax',
    },
    {
      id: 34,
      question: 'Which of these is not a programming language?',
      options: ['Python', 'Java', 'HTML', 'C++'],
      correctAnswer: 'HTML',
    },
    {
      id: 35,
      question: "The 'Rowlatt Act' was passed in which year?",
      options: ['1917', '1919', '1921', '1923'],
      correctAnswer: '1919',
    },
    {
      id: 36,
      question: 'What is the unit of measurement for the frequency of sound?',
      options: ['Decibel', 'Hertz', 'Watt', 'Pascal'],
      correctAnswer: 'Hertz',
    },
    {
      id: 37,
      question: 'Which of the following is a symptom of jaundice?',
      options: ['Reddening of skin', 'Yellowing of skin and eyes', 'Paleness of skin', 'Rashes on skin'],
      correctAnswer: 'Yellowing of skin and eyes',
    },
    {
      id: 38,
      question: 'The "Panchayati Raj" system was first introduced in which state?',
      options: ['Rajasthan', 'Andhra Pradesh', 'Gujarat', 'Uttar Pradesh'],
      correctAnswer: 'Rajasthan',
    },
    {
      id: 39,
      question: 'In which year did the World War I begin?',
      options: ['1912', '1914', '1916', '1918'],
      correctAnswer: '1914',
    },
    {
      id: 40,
      question: 'What is the pH range of an acidic solution?',
      options: ['Less than 7', 'Equal to 7', 'Greater than 7', 'Between 7 and 14'],
      correctAnswer: 'Less than 7',
    },
    {
      id: 41,
      question: 'Which of the following is a major component of biogas?',
      options: ['Oxygen', 'Methane', 'Hydrogen', 'Nitrogen'],
      correctAnswer: 'Methane',
    },
    {
      id: 42,
      question: 'The "Chipko movement" is associated with?',
      options: ['Water conservation', 'Forest conservation', 'Soil conservation', 'Wildlife protection'],
      correctAnswer: 'Forest conservation',
    },
    {
      id: 43,
      question: 'Who was the first Indian woman to climb Mount Everest?',
      options: ['Bachendri Pal', 'Santosh Yadav', 'Arunima Sinha', 'Premlata Agarwal'],
      correctAnswer: 'Bachendri Pal',
    },
    {
      id: 44,
      question: 'What is the main function of the Reserve Bank of India (RBI)?',
      options: ['Printing currency', 'Controlling inflation', 'Regulating the banking system', 'All of the above'],
      correctAnswer: 'All of the above',
    },
    {
      id: 45,
      question: 'Which Mughal Emperor was known as "Zinda Pir" (Living Saint)?',
      options: ['Akbar', 'Jahangir', 'Shah Jahan', 'Aurangzeb'],
      correctAnswer: 'Aurangzeb',
    },
    {
      id: 46,
      question: 'The "Ozone layer" protects us from which harmful radiation from the sun?',
      options: ['Infrared rays', 'Ultraviolet rays', 'X-rays', 'Gamma rays'],
      correctAnswer: 'Ultraviolet rays',
    },
    {
      id: 47,
      question: 'Which of the following is responsible for blood clotting?',
      options: ['Red Blood Cells', 'White Blood Cells', 'Platelets', 'Plasma'],
      correctAnswer: 'Platelets',
    },
    {
      id: 48,
      question: 'The headquarters of the World Health Organization (WHO) is located in?',
      options: ['New York', 'London', 'Geneva', 'Paris'],
      correctAnswer: 'Geneva',
    },
    {
      id: 49,
      question: 'Which is the largest democracy in the world?',
      options: ['USA', 'China', 'India', 'Russia'],
      correctAnswer: 'India',
    },
    {
      id: 50,
      question: 'Which of these is an example of a web browser?',
      options: ['Microsoft Word', 'Google Chrome', 'Photoshop', 'VLC Player'],
      correctAnswer: 'Google Chrome',
    },
    {
      id: 51,
      question: 'Which of the following is an example of a renewable resource?',
      options: ['Coal', 'Petroleum', 'Natural Gas', 'Solar Energy'],
      correctAnswer: 'Solar Energy',
    },
    {
      id: 52,
      question: 'What is the study of inscriptions called?',
      options: ['Numismatics', 'Epigraphy', 'Palaeography', 'Archaeology'],
      correctAnswer: 'Epigraphy',
    },
    {
      id: 53,
      question: 'The instrument used to measure atmospheric pressure is?',
      options: ['Thermometer', 'Barometer', 'Manometer', 'Hygrometer'],
      correctAnswer: 'Barometer',
    },
    {
      id: 54,
      question: 'Who gave the slogan "Inquilab Zindabad"?',
      options: ['Subhash Chandra Bose', 'Bhagat Singh', 'Mahatma Gandhi', 'Lala Lajpat Rai'],
      correctAnswer: 'Bhagat Singh',
    },
    {
      id: 55,
      question: 'Which part of the Indian Constitution is known as its "soul"?',
      options: ['Preamble', 'Fundamental Rights', 'Directive Principles', 'Fundamental Duties'],
      correctAnswer: 'Preamble',
    },
    {
      id: 56,
      question: 'What is the full form of AI?',
      options: ['Automated Intelligence', 'Artificial Intelligence', 'Algorithmic Intelligence', 'Analytical Intelligence'],
      correctAnswer: 'Artificial Intelligence',
    },
    {
      id: 57,
      question: 'Which of these is a noble gas?',
      options: ['Hydrogen', 'Oxygen', 'Helium', 'Nitrogen'],
      correctAnswer: 'Helium',
    },
    {
      id: 58,
      question: 'The "Battle of Buxar" was fought in which year?',
      options: ['1757', '1764', '1772', '1781'],
      correctAnswer: '1764',
    },
    {
      id: 59,
      question: 'Which planet is known as the "Blue Planet"?',
      options: ['Mars', 'Venus', 'Earth', 'Neptune'],
      correctAnswer: 'Earth',
    },
    {
      id: 60,
      question: 'The "Laws of Motion" were given by?',
      options: ['Galileo', 'Newton', 'Kepler', 'Einstein'],
      correctAnswer: 'Newton',
    },
    {
      id: 61,
      question: 'What is the main component of vinegar?',
      options: ['Citric Acid', 'Acetic Acid', 'Lactic Acid', 'Formic Acid'],
      correctAnswer: 'Acetic Acid',
    },
    {
      id: 62,
      question: 'Who was the first Governor-General of independent India?',
      options: ['Lord Mountbatten', 'C. Rajagopalachari', 'Jawaharlal Nehru', 'Dr. Rajendra Prasad'],
      correctAnswer: 'Lord Mountbatten',
    },
    {
      id: 63,
      question: 'What is the chemical name for laughing gas?',
      options: ['Methane', 'Nitrous Oxide', 'Carbon Monoxide', 'Sulphur Dioxide'],
      correctAnswer: 'Nitrous Oxide',
    },
    {
      id: 64,
      question: 'The "Right to Information" Act in India was passed in which year?',
      options: ['2002', '2005', '2008', '2010'],
      correctAnswer: '2005',
    },
    {
      id: 65,
      question: 'Which acid is present in an ant sting?',
      options: ['Acetic Acid', 'Formic Acid', 'Citric Acid', 'Lactic Acid'],
      correctAnswer: 'Formic Acid',
    },
    {
      id: 66,
      question: 'The "World Environment Day" is celebrated on?',
      options: ['April 22', 'June 5', 'July 11', 'December 10'],
      correctAnswer: 'June 5',
    },
    {
      id: 67,
      question: 'What is the phenomenon that makes a pencil appear bent in a glass of water?',
      options: ['Reflection', 'Refraction', 'Dispersion', 'Diffraction'],
      correctAnswer: 'Refraction',
    },
    {
      id: 68,
      question: 'The headquarters of SAARC is located in?',
      options: ['New Delhi', 'Kathmandu', 'Dhaka', 'Islamabad'],
      correctAnswer: 'Kathmandu',
    },
    {
      id: 69,
      question: 'Which of the following is not a part of the Union Executive?',
      options: ['The President', 'The Prime Minister', 'The Speaker of the Lok Sabha', 'The Council of Ministers'],
      correctAnswer: 'The Speaker of the Lok Sabha',
    },
    {
      id: 70,
      question: 'In which layer of the atmosphere do most weather phenomena occur?',
      options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'],
      correctAnswer: 'Troposphere',
    },
    {
      id: 71,
      question: 'What is the currency of the United Kingdom?',
      options: ['Euro', 'Dollar', 'Pound Sterling', 'Yen'],
      correctAnswer: 'Pound Sterling',
    },
    {
      id: 72,
      question: 'Which of the following diseases is caused by a virus?',
      options: ['Tuberculosis', 'Cholera', 'COVID-19', 'Malaria'],
      correctAnswer: 'COVID-19',
    },
    {
      id: 73,
      question: 'The term "bulls and bears" is associated with?',
      options: ['Banking', 'Foreign exchange', 'Stock market', 'Insurance'],
      correctAnswer: 'Stock market',
    },
    {
      id: 74,
      question: 'Who founded the Brahmo Samaj?',
      options: ['Raja Ram Mohan Roy', 'Dayananda Saraswati', 'Swami Vivekananda', 'Ishwar Chandra Vidyasagar'],
      correctAnswer: 'Raja Ram Mohan Roy',
    },
    {
      id: 75,
      question: 'Which of these is not a classical dance form of India?',
      options: ['Kathak', 'Bhangra', 'Odissi', 'Mohiniyattam'],
      correctAnswer: 'Bhangra',
    },
    {
      id: 76,
      question: 'The process of producing energy in the Sun is?',
      options: ['Nuclear Fission', 'Nuclear Fusion', 'Combustion', 'Radioactive decay'],
      correctAnswer: 'Nuclear Fusion',
    },
    {
      id: 77,
      question: 'What is the full form of URL?',
      options: ['Uniform Resource Locator', 'Universal Resource Locator', 'Uniform Resource Link', 'Universal Resource Link'],
      correctAnswer: 'Uniform Resource Locator',
    },
    {
      id: 78,
      question: 'Which of the following is a metalloid?',
      options: ['Gold', 'Silicon', 'Carbon', 'Lead'],
      correctAnswer: 'Silicon',
    },
    {
      id: 79,
      question: 'The "Simon Commission" was appointed in India to?',
      options: ['Review the education system', 'Discuss constitutional reforms', 'Analyze the economic condition', 'Address social issues'],
      correctAnswer: 'Discuss constitutional reforms',
    },
    {
      id: 80,
      question: 'Which is the smallest country in the world by area?',
      options: ['Monaco', 'Nauru', 'Vatican City', 'San Marino'],
      correctAnswer: 'Vatican City',
    },
    {
      id: 81,
      question: 'The "Theory of Evolution" was proposed by?',
      options: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Robert Hooke'],
      correctAnswer: 'Charles Darwin',
    },
    {
      id: 82,
      question: 'Which river is known as the "Sorrow of Bengal"?',
      options: ['Ganges', 'Brahmaputra', 'Damodar', 'Hooghly'],
      correctAnswer: 'Damodar',
    },
    {
      id: 83,
      question: 'What is the SI unit of power?',
      options: ['Joule', 'Watt', 'Newton', 'Pascal'],
      correctAnswer: 'Watt',
    },
    {
      id: 84,
      question: 'The "Fundamental Duties" were added to the Indian Constitution by which amendment?',
      options: ['42nd Amendment', '44th Amendment', '24th Amendment', '1st Amendment'],
      correctAnswer: '42nd Amendment',
    },
    {
      id: 85,
      question: 'Which alloy is used for making aircraft bodies?',
      options: ['Brass', 'Bronze', 'Duralumin', 'Steel'],
      correctAnswer: 'Duralumin',
    },
    {
      id: 86,
      question: 'Who was the first Indian to win a Nobel Prize?',
      options: ['C. V. Raman', 'Rabindranath Tagore', 'Mother Teresa', 'Amartya Sen'],
      correctAnswer: 'Rabindranath Tagore',
    },
    {
      id: 87,
      question: 'What is the study of coins called?',
      options: ['Epigraphy', 'Numismatics', 'Palaeography', 'Cartography'],
      correctAnswer: 'Numismatics',
    },
    {
      id: 88,
      question: 'Which of these is a storage device?',
      options: ['CPU', 'RAM', 'Hard Disk Drive', 'Monitor'],
      correctAnswer: 'Hard Disk Drive',
    },
    {
      id: 89,
      question: 'The "Deficiency of Iodine" leads to which disease?',
      options: ['Scurvy', 'Goitre', 'Rickets', 'Beriberi'],
      correctAnswer: 'Goitre',
    },
    {
      id: 90,
      question: "What is the value of 'g' (acceleration due to gravity) on the surface of the Earth?",
      options: ['9.8 m/s²', '8.9 m/s²', '10 m/s²', '9.6 m/s²'],
      correctAnswer: '9.8 m/s²',
    },
  ],
};
